In [27]:
from data import DataLoader

In [28]:
data_loader = DataLoader()

In [29]:
# data_loader.download_dataset()

In [30]:
data_loader.split_data()
X_train, y_train = data_loader.get_train_data()
X_train, y_train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([1, 0, 1, ..., 7, 6, 9]))

In [31]:
X_train.shape, y_train.shape
X_train[:100, :].shape

(100, 784)

In [32]:
from model import Model
from activations import *
from layers import *
from losses import *
import numpy as np

In [33]:
model = Model([Linear(X_train.shape[1],10),Sigmoid(),Linear(10,1),Sigmoid()],MSELoss(), model_name='Model_2')

AttributeError: The model with name Model_2 already exist

In [26]:
res = model.forward(X_train[:100, :])

ValueError: shapes (10,784) and (100,784) not aligned: 784 (dim 1) != 100 (dim 0)

In [25]:
res

array([[0.66790806, 0.12331956, 0.9884538 , 0.85153938, 0.82516068,
        0.94415454, 0.65287761, 0.84912539, 0.35904642, 0.69098275,
        0.90822125, 0.93551731, 0.5581625 , 0.95528306, 0.10109926,
        0.18690327, 0.84375963, 0.96411678, 0.95090365, 0.1174039 ,
        0.79955585, 0.80718306, 0.13808326, 0.53856884, 0.11232185,
        0.58229947, 0.93820191, 0.38355788, 0.62488314, 0.69757757,
        0.27393717, 0.63775711, 0.78116114, 0.9284277 , 0.56967723,
        0.84929126, 0.86149557, 0.80232804, 0.79915026, 0.80704525,
        0.83327122, 0.79640804, 0.86884617, 0.98917396, 0.1796977 ,
        0.93296163, 0.70259638, 0.89304888, 0.15799605, 0.42980057,
        0.93689543, 0.41507824, 0.89028699, 0.7732223 , 0.40187296,
        0.66767785, 0.75438045, 0.83763768, 0.83322131, 0.8164728 ,
        0.94085212, 0.99360705, 0.23077934, 0.44023048, 0.66564168,
        0.59857838, 0.76636953, 0.43017353, 0.8605273 , 0.65731608,
        0.86305586, 0.07886429, 0.82961511, 0.92